# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1441333589);
user_pref("app.update.lastUpdateTime.background-update-timer", 1441333349);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1441333709);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1441333109);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1441333469);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1441333229);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 24);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150108202552");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 6324);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20150108202552");
user_pref("browser.startup.homepage_override.mstone", "35.0");
user_pref("browser.taskbar.lastgroupid", "308046B0AF4A39CB");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button-throttled\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":3,\"newElementCount\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1441419388978");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1441333056243");
user_pref("datareporting.policy.firstRunTime", "1441332988978");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 3994);
user_pref("datareporting.sessions.current.main", 320);
user_pref("datareporting.sessions.current.sessionRestored", 4539);
user_pref("datareporting.sessions.current.startTime", "1441434226477");
user_pref("datareporting.sessions.current.totalTime", 8);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1441332987797,\"a\":24,\"t\":924,\"c\":true,\"m\":186,\"fp\":7709,\"sr\":8440}");
user_pref("distribution.mozilla26.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:35.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1441333592);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150402.01");
user_pref("extensions.lastAppVersion", "35.0");
user_pref("extensions.lastPlatformVersion", "35.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"winreg-app-user\":{\"{e4f94d1e-2f53-401e-8885-681602c0ddd8}\":{\"d\":\"C:\\\\ProgramData\\\\McAfee Security Scan\\\\Extensions\\\\{e4f94d1e-2f53-401e-8885-681602c0ddd8}.xpi\",\"e\":false,\"v\":\"1.0\",\"st\":1396607774000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"35.0\",\"st\":1428078530279,\"mt\":1428078530034}},\"winreg-app-global\":{\"detgdp@gmail.com\":{\"d\":\"C:\\\\Users\\\\biswajit\\\\AppData\\\\Roaming\\\\Mozilla\\\\Firefox\\\\Profiles\\\\jucb1oz6.default\\\\extensions\\\\detgdp@gmail.com\",\"e\":false,\"v\":\"1.0.0\",\"st\":1417059535087,\"mt\":1413445570000},\"istart_ffnt@gmail.com\":{\"d\":\"D:\\\\Study_Material\\\\Python\\\\WingsIDE\\\\extensions\\\\istart_ffnt@gmail.com\",\"e\":false,\"v\":\"5.3.7\",\"st\":1428044504161,\"mt\":1426764906000},\"fiddlerhook@fiddler2.com\":{\"d\":\"C:\\\\Program Files\\\\Fiddler2\\\\FiddlerHook\",\"e\":false,\"v\":\"2.4.9.7\",\"st\":1431239132801,\"mt\":1416625068000},\"quick_searchff@gmail.com\":{\"d\":\"D:\\\\Study_Material\\\\Python\\\\WingsIDE\\\\extensions\\\\quick_searchff@gmail.com\",\"e\":false,\"v\":\"5.4.13\",\"st\":1432175233009,\"mt\":1432033982000},\"sweetsearch@gmail.com\":{\"d\":\"D:\\\\Study_Material\\\\Python\\\\WingsIDE\\\\extensions\\\\sweetsearch@gmail.com\",\"e\":false,\"v\":\"1.0.0.1031\",\"st\":1432175244670,\"mt\":1429006078000},\"default_newtabff@gmail.com\":{\"d\":\"D:\\\\Study_Material\\\\Python\\\\WingsIDE\\\\extensions\\\\default_newtabff@gmail.com\",\"e\":false,\"v\":\"5.4.21\",\"st\":1437582972097,\"mt\":1436779750000}}}");
user_pref("gecko.buildID", "20150108202552");
user_pref("gecko.mstone", "35.0");
user_pref("gfx.blacklist.direct2d", 3);
user_pref("loop.soft_start_ticket_number", 10153794);
user_pref("loop.throttled2", false);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1441333060);
user_pref("media.gmp-gmpopenh264.version", "1.3");
user_pref("media.gmp-manager.lastCheck", 1441333057);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.http.atsvc.enabled", false);
user_pref("network.http.atsvc.oe", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 93692);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1441434226);
user_pref("toolkit.telemetry.previousBuildID", "20150108202552");
